routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\DashboardController as AdminDashboard;
use App\Http\Controllers\Admin\RoleController as AdminRole;
use App\Http\Controllers\Admin\UserController as AdminUser;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('home');
});

Route::prefix('admin')->middleware(['auth'])->group(function () {
    Route::get('/dashboard', [AdminDashboard::class, 'index'])->name('dashboard.index');

    Route::resource('roles', AdminRole::class);
    Route::resource('users', AdminUser::class);
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Str;
use Carbon\Carbon;

use Spatie\Permission\Models\Role as SpatieRole;
use App\Models\Concerns\UuidTrait;

class Role extends SpatieRole
{
    use HasFactory, UuidTrait;

    protected $fillable = [
        'id',
        'name',
        'guard_name',
    ];

    protected $primaryKey = 'id';
    protected $keyType = 'string';
    public $incrementing = false;

    const ADMIN = 'Admin';

    public function getCreatedAtFormattedAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->format('d, M Y H:i:s');
    }

    public function getUpdatedAtFormattedAttribute()
    {
        return Carbon::parse($this->attributes['updated_at'])->format('d, M Y H:i:s');
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use Nwidart\Modules\Facades\Module;

use App\Http\Requests\Admin\RoleRequest;

use App\Repositories\Admin\Interfaces\RoleRepositoryInterface;
use App\Repositories\Admin\Interfaces\PermissionRepositoryInterface;

use App\Models\Role;
use App\Authorizable;

class RoleController extends Controller
{
    use Authorizable;

    private $roleRepository;
    private $permissionRepository;

    public function __construct(RoleRepositoryInterface $roleRepository, PermissionRepositoryInterface $permissionRepository) // phpcs:ignore
    {
        parent::__construct();

        $this->roleRepository = $roleRepository;
        $this->permissionRepository = $permissionRepository;

        $this->data['currentAdminMenu'] = 'roles';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $options = [
            'per_page' => $this->perPage,
            'order' => [
                'name' => 'asc',
            ]
        ];

        $this->data['roles'] = $this->roleRepository->findAll($options);

        return view('admin.roles.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->initModules();
        $this->data['permissions'] = $this->permissionRepository->findAll();
        return view('admin.roles.form', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        $params = $request->validated();

        if ($this->roleRepository->create($params)) {
            return redirect('admin/roles')
                ->with('success', __('roles.success_create_message'));
        }

        return redirect('admin/roles/create')
            ->with('error', 'Role could not be saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->data['role'] = $this->roleRepository->findById($id);
        return view('admin.roles.show', $this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->initModules();
        $role = $this->roleRepository->findById($id);

        $this->data['role'] = $role;
        $this->data['permissions'] = $this->permissionRepository->findAll();
        $this->data['disabled'] = ($role->name == Role::ADMIN) ? 'disabled' : '';

        return view('admin.roles.form', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RoleRequest $request, $id)
    {
        $role = $this->roleRepository->findById($id);

        if ($this->roleRepository->update($id, $request->validated())) {
            return redirect('admin/roles')
                ->with('success', __('roles.success_updated_message', ['name' => $role->name]));
        }

        return redirect('admin/roles')
                ->with('error', __('roles.fail_to_update_message', ['name' => $role->name]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = $this->roleRepository->findById($id);

        if ($this->roleRepository->delete($id)) {
            return redirect('admin/roles')
                ->with('success', __('roles.success_deleted_message', ['name' => $role->name]));
        }

        return redirect('admin/roles')
                ->with('error', __('roles.fail_to_delete_message', ['name' => $role->name]));
    }


    private function initModules()
    {
        $modules = Module::getOrdered();
        $moduleAdminMenus = [];

        if ($modules) {
            foreach ($modules as $module) {
                $this->initModulePermissions($module);
            }
        }
    }

    private function getModuleDetails($module)
    {
        $moduleJson = $module->getPath(). '/module.json';
        return json_decode(file_get_contents($moduleJson), true);
    }

    private function initModulePermissions($module)
    {
        $moduleDetails = $this->getModuleDetails($module);
        if (!empty($moduleDetails['permissions'])) {
            foreach ($moduleDetails['permissions'] as $permission) {
                $this->initPermissionActions($permission);
            }
        }
    }

    private function initPermissionActions($permission)
    {
        $permissionMappings = ['view', 'add', 'edit', 'delete'];

        $permissionActions = [];
        foreach ($permissionMappings as $permissionMapping) {
            $name = $permissionMapping . '_' . $permission;
            $permissionActions[] = $this->permissionRepository->create(['name' => $name]);
        }

        $adminRole = $this->roleRepository->findByName('admin');
        $adminRole->givePermissionTo($permissionActions);
    }
}

resources/views/admin/roles/_filter.blade.php
<form method="GET" action="{{ route('users.index') }}">
    <div class="form-row">
        <div class="form-group col-md-2 offset-md-10">
            <a href="{{ url('admin/roles/create') }}" class="btn btn-block btn-icon icon-left btn-success btn-filter"><i class="fas fa-plus-circle"></i> @lang('general.btn_create_label')</a>
        </div>
    </div>
</form>

resources/views/admin/roles/_permissions.blade.php
<div class="row">
    @foreach($permissions as $perm)
        <?php
            $per_found = null;

            if( isset($role) ) {
                $per_found = $role->hasPermissionTo($perm->name);
            }

            if( isset($user)) {
                $per_found = $user->hasDirectPermission($perm->name);
            }

            $labelName = Str::of($perm->name)->replace('_', ' ');
        ?>
        <div class="col-sm-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="permissions[]" id="{{ $perm->id }}" value="{{ $perm->name }}" {{  ($per_found == true ? ' checked' : '') }} {{ $disabled ?? '' }}>
                <label class="form-check-label {{ Str::contains($perm->name, 'delete') ? 'text-danger' : '' }}" for="{{ $perm->id }}">
                    {{ $labelName }}
                </label>
            </div>
        </div>
    @endforeach
</div>

resources/views/admin/roles/form.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>@lang('roles.role_management')</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="{{ url('admin/roles') }}">@lang('roles.role_management')</a></div>
            <div class="breadcrumb-item active"><a href="{{ url('admin/roles/create') }}">@lang('roles.role_add_new')</a></div>
        </div>
    </div>
    @if (empty($role))
        <form method="POST" action="{{ url('admin/roles') }}">
    @else
        <form method="POST" action="{{ route('roles.update', $role->id) }}">
        <input type="hidden" name="id" value="{{ $role->id }}"/>
        @method('PUT')
    @endif
    @csrf
        <div class="section-body">
            <h2 class="section-title">{{ empty($role) ? __('roles.role_add_new') : __('roles.role_update') }}</h2>
            <div class="row">
                <div class="col-lg-3">
                    <div class="card">
                        <div class="card-header">
                            <h4>{{ empty($role) ? __('roles.add_card_title') : __('roles.update_card_title') }}</h4>
                        </div>
                        <div class="card-body">
                            @include('admin.shared.flash')
                            <div class="form-group">
                                <label>@lang('roles.name_label')</label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror @if (!$errors->has('name') && old('name')) is-valid @endif" value="{{ old('name', !empty($role) ? $role->name : null) }}" {{ $disabled ?? '' }}>
                                @error('name')
                                    <div class="invalid-feedback">
                                    {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary">{{ empty($role) ? __('general.btn_create_label') : __('general.btn_update_label') }}</button>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="card">
                        <div class="card-header">
                            <h4>{{ __('roles.set_role_permissions_label') }}</h4>
                        </div>
                        <div class="card-body">
                            @include('admin.roles._permissions', ['disabled' => $disabled ?? ''])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>@lang('roles.role_management')</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></div>
            <div class="breadcrumb-item active"><a href="{{ url('admin/roles') }}">@lang('roles.role_management')</a></div>
        </div>
    </div>
    <div class="section-body">
        <h2 class="section-title">@lang('roles.role_list')</h2>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4>@lang('roles.role_management')</h4>
                    </div>
                    <div class="card-body">
                        @include('admin.shared.flash')
                        @include('admin.roles._filter')
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-md">
                                <thead>
                                    <th>@lang('roles.name_label')</th>
                                    <th>@lang('roles.guard_name_label')</th>
                                    <th>@lang('roles.updated_at_label')</th>
                                    <th width="25%">@lang('general.action_label')</th>
                                </thead>
                                <tbody>
                                    @forelse ($roles as $role)
                                        <tr>
                                            <td>{{ $role->name}}</td>
                                            <td>{{ $role->guard_name}}</td>
                                            <td>{{ $role->updated_at_formatted}}</td>
                                            <td>
                                                <a class="btn btn-sm btn-info" href="{{ url('admin/roles/'. $role->id)}}"><i class="far fa-eye"></i> @lang('general.btn_show_label') </a>
                                                <a class="btn btn-sm btn-warning" href="{{ url('admin/roles/'. $role->id .'/edit')}}"><i class="far fa-edit"></i> @lang('general.btn_edit_label') </a>
                                                <a href="{{ url('admin/roles/'. $role->id) }}" class="btn btn-sm btn-danger" onclick="
                                                    event.preventDefault();
                                                    if (confirm('Do you want to remove this?')) {
                                                        document.getElementById('delete-role-{{ $role->id }}').submit();
                                                    }">
                                                    <i class="far fa-trash-alt"></i> @lang('general.btn_delete_label')
                                                </a>
                                                <form id="delete-role-{{ $role->id }}" action="{{ url('admin/roles/'. $role->id) }}" method="POST">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    @csrf
                                                </form>
                                            </td>
                                        </tr>
                                    @empty
                                        
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                        {{ $roles->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>@lang('roles.role_management')</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></div>
            <div class="breadcrumb-item active"><a href="{{ url('admin/roles') }}">@lang('roles.role_management')</a></div>
        </div>
    </div>
    <div class="section-body">
        <h2 class="section-title">@lang('roles.role_list')</h2>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Role Detail</h4>
                    </div>
                    <div class="card-body">
                        @include('admin.shared.flash')
                        <div class="form-row">
                            <div class="col-md-2">
                                <Label>Name</Label>
                            </div>
                            <div class="col-md-10">
                                : {{ $role->name }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-2">
                                <Label>Guard</Label>
                            </div>
                            <div class="col-md-10">
                                : {{ $role->guard_name }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-2">
                                <Label>Created</Label>
                            </div>
                            <div class="col-md-10">
                                : {{ $role->created_at_formatted }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-2">
                                <Label>Updated</Label>
                            </div>
                            <div class="col-md-10">
                                : {{ $role->updated_at_formatted }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection